<div class="auth-page">
    <section class="auth-form">
    <h2>Connexion</h2>
    <?php if (!empty($error)): ?>
        <p class="error"><?= $error ?></p>
    <?php endif; ?>
    <form action="/Spoil-Me/?route=check-login" method="post">
        <input type="email" name="email" placeholder="Email" required>
        <input type="password" name="password" placeholder="Mot de passe" required>
        <div class="auth-form-actions">
            <button type="submit">Se connecter</button>
            <p>Pas encore de compte ? <a href="/Spoil-Me/?route=register">S'inscrire</a></p>
        </div>
    </form>
    </section>
</div>
